#!/usr/bin/ruby
# coding: utf-8
#Usage: add-entry-to-db db-name id-of-entry (other-fields)
require 'csv'

if (ARGV.length < 2)
  print "<Insufficient Arguments>"
  exit 0
end

#Controlliamo prima se l'id è già presente
res = `/etc/asterisk/calllist/is-id-in-db #{ARGV[0]} #{ARGV[1]}`;
if (res == "<True>")
   print "<Already In>"
   exit 0
end

#Inseriamo il record
record = [];
for i in 1...(ARGV.length)
  record << ARGV[i];
end

CSV.open("/etc/asterisk/calllist/dbs/#{ARGV[0]}", "a+") do |csv|
  csv << record;
end
print "<Added>"
exit 0
			   
